# print("hello")

# while True:
#     operator=int(input("enter a required operator , that is 1.sum 2.sub 3.multiply 4.division 5.exit = "))
#     num1=float(input("enter a 1 num: "))
#     num2=float(input("enter a 2 num: "))
#     if operator == 1 :
#         print(f"answer is {num1+num2}")
#     elif operator == 2 :
#         print(f"answer is {num1-num2}")
#     elif operator == 3 :
#         print(f"answer is {num1*num2}")
#     elif operator == 4 and num2!=0 :
#         print(f"answer is {num1/num2}")
#         if num2 == 0 :
#              print("answer is not defined")

#     elif operator == 5 :
#         break
# print("you are now exited from the loop") 


